apiVersion: batch/v1
kind: CronJob
metadata:
  name: temp-cleaner
spec:
  schedule: "* * * * *" #	Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: temp-cleaner
              image: busybox:latest
              command:
                - /bin/sh
                - -c
                - date; echo Hello!
          restartPolicy: OnFailure