apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-demo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/k8s-storage-demo-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-demo-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi