apiVersion: v1
kind: Pod
metadata:
  name: storage-demo-pod
spec:
  volumes:
    - name: ephemeral-logs
      emptyDir: {}
    - name: persistent-data
      persistentVolumeClaim:
        claimName: storage-demo-pvc
  containers:
    - name: nginx
      image: nginx-storage-demo:1.0
      imagePullPolicy: IfNotPresent
      ports:
          - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/upload
          name: persistent-data
        - mountPath: /var/log/nginx
          name: ephemeral-logs