apiVersion: v1
kind: Pod
metadata:
  name: multi-container-app
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'echo "Initializing shared volume" > /shared-logs/init.log']
      volumeMounts:
        - name: shared-logs
          mountPath: /shared-logs
  containers:
    - name: nginx
      image: nginx-multi-container-app:1.0
      ports:
            - containerPort: 80
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
    - name: log-tailer
      image: busybox
      command: ['sh', '-c', 'tail -f /shared-logs/init.log']
      volumeMounts:
        - name: shared-logs
          mountPath: /shared-logs